// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShaTask.Models
{
    public partial class InvoiceDetail
    {
        public long Id { get; set; }
        public long InvoiceHeaderId { get; set; }
        public /*int*/ long ItemId { get; set; }
        public double ItemCount { get; set; }
        public double ItemPrice { get; set; }

        public virtual InvoiceHeader InvoiceHeader { get; set; }
        public virtual Item Item { get; set; }
    }
}